# Generated by Django 3.2.8 on 2021-11-04 16:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_item_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 4, 18, 14, 31, 377788), null=True),
        ),
    ]
