# Generated by Django 2.2.12 on 2021-11-02 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(help_text='Enter a short description of the item', max_length=255)),
                ('item_description', models.TextField(help_text='Enter a brief description of the item', max_length=1200)),
                ('item_image', models.ImageField(upload_to='auctions/static/itemimage')),
                ('created', models.DateTimeField(editable=False, null=True)),
                ('expires', models.DateTimeField(editable=False, null=True)),
                ('item_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.Category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateTimeField(editable=False, null=True)),
                ('expires', models.DateTimeField(editable=False, null=True)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.Item')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Auction_Winner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
