# Generated by Django 3.2.8 on 2021-11-03 20:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20211103_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_price',
            field=models.DecimalField(decimal_places=2, default=0.1, max_digits=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 3, 22, 14, 38, 969581), null=True),
        ),
    ]
