# Generated by Django 3.2.8 on 2021-11-04 16:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auto_20211104_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_id',
            field=models.AutoField(default=0, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 4, 18, 11, 3, 628915), null=True),
        ),
    ]
