# Generated by Django 2.2.12 on 2021-11-05 08:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20211105_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 5, 8, 43, 59, 508533), null=True),
        ),
    ]
