# Generated by Django 2.2.12 on 2021-11-03 12:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20211103_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 3, 12, 45, 26, 334324), null=True),
        ),
    ]
