# Generated by Django 3.2.8 on 2021-11-06 15:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_alter_item_expires'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item_price',
            new_name='item_bid',
        ),
        migrations.AlterField(
            model_name='item',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 6, 17, 18, 26, 470573), null=True),
        ),
    ]
