# Generated by Django 3.2.8 on 2021-11-06 15:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auto_20211106_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 6, 17, 18, 36, 763070), null=True),
        ),
    ]
