# Generated by Django 3.2.8 on 2021-11-06 17:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_alter_item_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 6, 19, 52, 40, 461215), null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_bid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
