# Generated by Django 3.2.8 on 2021-11-06 20:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_auto_20211106_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 6, 22, 48, 56, 157600), null=True),
        ),
    ]
