# Generated by Django 3.2.8 on 2021-11-07 17:47

import datetime
from django.db import migrations, models
import uuid

class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_alter_item_expires'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_code',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 7, 19, 47, 38, 640345), null=True),
        ),
    ]
