# Generated by Django 3.2.8 on 2021-11-07 18:07

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_auto_20211107_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 7, 20, 7, 26, 383602), null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_code',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=False),
        ),
    ]
