# Generated by Django 3.2.8 on 2021-11-07 18:11

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_auto_20211107_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 7, 20, 11, 3, 796271), null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_code',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36, null=True),
        ),
    ]
