# Generated by Django 3.2.8 on 2021-11-07 18:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0020_alter_item_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 7, 20, 12, 52, 766567), null=True),
        ),
    ]
