# Generated by Django 3.2.8 on 2021-11-07 18:15

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0021_alter_item_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 7, 20, 15, 31, 968203), null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
