# Generated by Django 3.2.8 on 2021-11-07 18:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0022_auto_20211107_2015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item_code',
            new_name='item_UUID',
        ),
        migrations.AlterField(
            model_name='item',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 7, 20, 39, 16, 154556), null=True),
        ),
    ]
