# Generated by Django 2.2.12 on 2021-11-08 09:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0028_auto_20211108_0847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='item',
        ),
        migrations.AlterField(
            model_name='item',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 8, 9, 35, 13, 70024), null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_bid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.Bid'),
        ),
    ]
