# Generated by Django 2.2.12 on 2021-11-08 10:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0030_auto_20211108_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_bid_link',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='auctions.Bid'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 8, 10, 5, 32, 635968), null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_bid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
