# Generated by Django 2.2.12 on 2021-11-08 10:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0031_auto_20211108_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_bid_link',
        ),
        migrations.AlterField(
            model_name='item',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 8, 10, 7, 32, 981148), null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_bid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.Bid'),
        ),
    ]
