# Generated by Django 3.2.8 on 2021-11-08 18:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0034_auto_20211108_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='item',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='auctions.item'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 8, 20, 47, 23, 371639), null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_bid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
