# Generated by Django 3.2.8 on 2021-11-08 18:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0036_alter_item_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 8, 20, 56, 42, 621743), null=True),
        ),
    ]
