# Generated by Django 3.2.8 on 2021-11-08 19:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0037_alter_item_expires'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_start_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 8, 21, 24, 12, 793715), null=True),
        ),
    ]
