# Generated by Django 2.2.12 on 2021-11-09 13:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0044_auto_20211109_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 9, 13, 36, 42, 714820), null=True),
        ),
    ]
