# Generated by Django 2.2.12 on 2021-11-09 13:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0045_auto_20211109_1336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item_last_bid',
            new_name='item_current_price',
        ),
        migrations.AlterField(
            model_name='item',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 9, 13, 41, 13, 421100), null=True),
        ),
    ]
