# Generated by Django 3.2.8 on 2021-11-09 20:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0048_alter_item_expires'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='item',
        ),
        migrations.AddField(
            model_name='favorite',
            name='item',
            field=models.ManyToManyField(blank=True, related_name='auctions_in_the_watchlist', to='auctions.Item'),
        ),
        migrations.AlterField(
            model_name='item',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 9, 22, 21, 39, 110565), null=True),
        ),
    ]
