# Generated by Django 3.2.8 on 2021-11-09 21:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0049_auto_20211109_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 9, 23, 7, 21, 403126), null=True),
        ),
    ]
