# Generated by Django 2.2.12 on 2021-11-11 13:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0051_auto_20211110_0804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='item',
        ),
        migrations.AddField(
            model_name='favorite',
            name='item',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='auctions.Item'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 11, 13, 8, 49, 559892), null=True),
        ),
    ]
